---
title: "Customizable Resumes with R Tools"
author: "Kristina Riemer"
format: 
  uaz-revealjs:
      logo: "_extensions/cct-datascience/uaz/logo.png"
editor: source
---

## Overview {.smaller}

| Topic                                | Time          |
|:-------------------------------------|:--------------|
| Welcome & intros                     | 11:00 - 11:05 |
| What are R tool options for resumes? | 11:05 - 11:15 |
| Overview of `datadrivencv`           | 11:15 - 11:45 |
| Create resumes                       | 11:45 - 11:55 |
| Customize resumes                    | 12:05 - 12:35 |
| BREAK                                | 12:35 - 12:45 |

# Welcome!

## CCT Data Science Team

#### Supporting reproducible research, data pipelines, and software development in ALVSCE

::: incremental
-   Workshops
-   Drop-in hours
-   "Incubator" program
-   Longer-term collaborations
-   Learn more: <https://datascience.cct.arizona.edu>
:::

## Before we get started {.smaller}

::: incremental
-   These slides (and links!) are available at: \<\>
-   Please make sure you have R and RStudio installed
- Additionally will need `datadrivencv` R packaged installed
  - To do so, use `devtools::install_github("cct-datascience/datadrivencv")`
  - This requires having `devtools` R package installed
:::

## Learning objectives

::: incremental
We will not be learning: 
- what *content* your CV or resume should have
- how to program in the R language

:::

## Learning objectives

::: incremental
We will be learning: 
- the pros and cons of different R tools for creating custom resumes
- about how to use the `datadrivencv` R package to create and customize resumes
- 

You should be able to leave this workshop with a custom (though probably not complete) resume!


:::


## Current options in R for creating resumes

(table)

## datadrivencv overview

## some history

not maintained, so installing can be finicky
we made our own version of it to fix these problems
if you have problems with this in future, create issue in repo or email us and we will try to keep a working version

## check installations

we have an alternative route if people can't / don't want to get `datadrivencv` installed

## Create generic CV from blank input data

```
library(datadrivencv)
use_datadriven_cv(full_name = "Your Name", data_location = "https://docs.google.com/spreadsheets/d/1mq7H8ZiF6k7H_f6rY2eA0sq2Xyxf9msmXv3LPsvSYoo/edit#gid=1730172225")
```

## Creates 4 files

::: incremental
automatically opens: 
- `cv.rmd`: 
- `render_cv.r`

created but not opened: 
- `dd_cv.css`: 
- `cv_printing_functions.r`: 
:::

## CCT Data Science opportunities

::: incremental
-   Drop-in hours - Tuesdays, 9-10
-   Incubator projects
-   Upcoming workshops
:::

## Data science \@ UA

::: incremental
-   [Research Bazaar Arizona](https://researchbazaar.arizona.edu/)
    -   Coffee & Code
    -   Hack Hour
-   UA Data Science Slack
    -   Sign up here: <https://jcoliver.github.io/uadatascience-slack/user-guide.html>
-   [UA Libraries Data & Viz Drop-In Hours](https://libcal.library.arizona.edu/event/10712327?_gl=1*23qnh9*_ga*MTcwMzYxNDQwNC4xNjk4MTYyODA2*_ga_7PV3540XS3*MTcwMTgwODgyNy44My4xLjE3MDE4MDk0OTUuMjkuMC4w)
-   UA Data Science Institute
:::

# Thank you!

Thank you for attending!

For details on drop-in hours, upcoming workshops, and Incubator Program offerings from CCT-Data Science, see our [website](https://datascience.cct.arizona.edu)!
