---
title: "Creating Lab Handbooks with Quarto"
author: "Eric R. Scott"
bibliography: references.bib
---

# Notes

The goal of this workshop is to provide a framework (Quarto book hosted on GitHub) for labs to create their own editable lab handbooks.

The workshop will consist of:
- an introductory lecture/discussion section briefly discussing the reasons for having a lab handbook, and relevant literature
- a hands-on setup section where participants will get set up with GitHub, create a GitHub organization (if applicable), and use the template to create their own repo
- explanation of how it all works—how to edit .qmd files with the visual editor, YAML, shortcodes, publishing to GitHub Pages, etc.
- time to make some edits.

## Learning objectives

-   understand the benefits of having a lab handbook
-   have a basic understanding of what git and github are
-   be able to edit files on GitHub
-   understand markdown basics
-   get a taste of the potential of Quarto (e.g. cross-refs, citations, callouts, etc.) and where to go for more info

## What goes in the slides

-   Summary of @tendler2023
    -   Benefits:
        -   Enables quality leadership
        -   articulating lab ethos is constructive
        -   creating it brings the lab together
        -   can aid recruitment
-   Figure 1 from @tendler2023
    -   Maybe modified with git/github terminology??
-   Many links to example lab handbooks and how to credit them if you lift text from them
-   What is Quarto and why is a quarto book hosted on github a good choice for this? (like, why not just make a word doc?)
    -   Quarto is useful for researchers (reproducible reports, manuscripts, professional websites, etc.)
    -   GitHub is useful for researchers (link to @braga2023)
    -   On GitHub, edits are versioned along with a required comment and can be explored and reverted
    -   Set up to automatically deploy to a website so can be easily shared to group members and recruits
- Getting started with git/GitHub using `usethis` (can re-cycle slides/notes from fall workshop series)
  - `usethis::git_sitrep()`
  - Shouldn't need a PAT since we won't do any PR stuff
